export const GAME_CORE_VERSION = '1.0.0'

export * from './types'
export * from './factories/catalog'
export * from './factories/cost'
export * from './factories/production'
export * from './warehouse/capacity'
export * from './land/layout'
export * from './land/specialSlots'
export * from './xp/level'
